### PR TITLE
Updated main.dart

### PR DESCRIPTION
**Pull request by Mansimar27**
Following changes have been made:-
* Made code more Efficient.
* Assigned theme to the App.
* Improved Indentations.
* Added App Title.
* Aligned App-bar title in center.
* Code is now more easy to read and understand.
* Added preferred device orientations.
* Layout Improvements.
* App is now more organised.

Happy to Contribute, I hope you would like these improvements.
I will be waiting to get this PR merged..!!

### CODE REVIEW

**Comment by Mansimar27** [comment]
No Functionality changes.
It's working perfectly!

**Comment by OnceAnum** [comment]
I checked this,
Perfectly working..
@eldadfux Check/Merge this PR.

**Comment by Mansimar27** [comment]
> I checked this,
> Perfectly working..
> @eldadfux Check/Merge this PR.

Thank You !

**Comment by lohanidamodar** [comment]
@Mansimar27 Thank you for your contribution however, I don't see any improvements that enhances the purpose of the playground. We want a simple and stupid way to explore Appwrite's functionalities.

- I don't see how the code is more readable than before just by changing themes and changing few layout widgets.
- I don't see how app is more organized can you explain?
- What benefit the appbar title in center has? it was already platform specific (center for iOS, left for Android by default by Flutter)
- How did you make code more efficient?
- How did you improve indentations?

**Pull request closed without merging**
