### PR TITLE
Fixed the link to contribution guide

### LINKED ISSUE #7: Link to Contribution guide
rename
The link to the contribution guide is not working.

### PR DESCRIPTION
**Pull request by rsrinath14**
closes #7 
Earlier the link to the contribution guide was not working.
rename

### CODE REVIEW

**Comment by eldadfux** [comment]
Thanks @srinath1412001! Have you already signed up for Appwrite SWAGS?

**Comment by rsrinath14** [comment]
Hey @eldadfux,
Yes I have registered for the swags. 
Thank you

**Comment by eldadfux** [comment]
Awesome! Looking forward to having more cool PRs 😃

**Comment by srinath1412001** [comment]
I'll will definitely try 😁

**Comment by rsrinath14** [comment]
I will definitely try 😁

**Pull request merged**
